-- rewind begin page null
CREATE TABLE `wp_amelia_appointments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `status` enum('approved','pending','canceled','rejected','no-show') DEFAULT NULL,
  `bookingStart` datetime NOT NULL,
  `bookingEnd` datetime NOT NULL,
  `notifyParticipants` tinyint(1) NOT NULL,
  `createPaymentLinks` tinyint(1) DEFAULT 1,
  `serviceId` int(11) NOT NULL,
  `packageId` int(11) DEFAULT NULL,
  `providerId` int(11) NOT NULL,
  `locationId` int(11) DEFAULT NULL,
  `internalNotes` mediumtext DEFAULT NULL,
  `googleCalendarEventId` varchar(255) DEFAULT NULL,
  `googleMeetUrl` varchar(255) DEFAULT NULL,
  `outlookCalendarEventId` varchar(255) DEFAULT NULL,
  `microsoftTeamsUrl` varchar(255) DEFAULT NULL,
  `appleCalendarEventId` varchar(255) DEFAULT NULL,
  `zoomMeeting` mediumtext DEFAULT NULL,
  `lessonSpace` mediumtext DEFAULT NULL,
  `parentId` int(11) DEFAULT NULL,
  `error` mediumtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('5','approved','2025-10-18 22:00:00','2025-10-18 22:30:00','1',NULL,'1',NULL,'1',NULL,'','o6tkupvom7qjvqumjknt9f121g',NULL,NULL,NULL,NULL,'{\"id\":82565054243,\"startUrl\":\"https:\\/\\/us02web.zoom.us\\/s\\/82565054243?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI4MjU2NTA1NDI0MyIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjVmYjM3NGIyM2JhYjQ4MGU5ODZlZjc2NGIxYjU5NzUxIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czAyIiwiZXhwIjoxNzYwODE1ODAwLCJpYXQiOjE3NjA4MDg2MDAsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.TIPKoGRcoik-pHip_cy35rDwaxKggKo35IL6GPA_CU8\",\"joinUrl\":\"https:\\/\\/us02web.zoom.us\\/j\\/82565054243?pwd=acbll5aGa73bijQMprHHJaZWXPb5YU.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('8','pending','2025-10-31 20:30:00','2025-10-31 21:00:00','1',NULL,'1',NULL,'1',NULL,'','7iq6o700frgqf0drl406si3nb8',NULL,NULL,NULL,NULL,'{\"id\":83040667679,\"startUrl\":\"https:\\/\\/us02web.zoom.us\\/s\\/83040667679?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI4MzA0MDY2NzY3OSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6ImE4MTVjOGM5YjIyNTRkYTRhMTNlYmI3YTAxMzVmZjExIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czAyIiwiZXhwIjoxNzYxOTQ5MzQ1LCJpYXQiOjE3NjE5NDIxNDUsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.VnHPTCK_EsTkOZDQe3cRo26mAMvPqo5cMDyYM4NAmuo\",\"joinUrl\":\"https:\\/\\/us02web.zoom.us\\/j\\/83040667679?pwd=XKnvpZYHiMpZLiewbFtK3QVlyzj2PK.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('10','pending','2025-11-01 19:30:00','2025-11-01 20:00:00','1',NULL,'1',NULL,'1',NULL,'','7rbk5a50j2lk5gu4a3ia1cd9fc',NULL,NULL,NULL,NULL,'{\"id\":81372014645,\"startUrl\":\"https:\\/\\/us02web.zoom.us\\/s\\/81372014645?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI4MTM3MjAxNDY0NSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6ImU5MTgzOTViM2VlMjRkZDNhZjgxNTM4YWM0NzNhZTU0Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czAyIiwiZXhwIjoxNzYxOTkwMDg0LCJpYXQiOjE3NjE5ODI4ODQsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.6gtFVqM1ww6ul7btJu8sYOShDiXxMrO1uHb9R-ezuFI\",\"joinUrl\":\"https:\\/\\/us02web.zoom.us\\/j\\/81372014645?pwd=yaKqbZxN7kqyaYWq5fvwJbB9RgY2Ma.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('12','pending','2025-11-06 22:00:00','2025-11-06 22:30:00','1',NULL,'1',NULL,'1',NULL,'','lv9odcfiv8s2pidqivb5c0ihig',NULL,NULL,NULL,NULL,'{\"id\":81215844933,\"startUrl\":\"https:\\/\\/us02web.zoom.us\\/s\\/81215844933?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI4MTIxNTg0NDkzMyIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjRjYmM5NmM4N2FhMTRmMjlhOGRlYzc4ZjkxYzZmYjUyIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czAyIiwiZXhwIjoxNzYyMzc2OTU5LCJpYXQiOjE3NjIzNjk3NTksImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.7sXDHpk30JgZ0XB9hMQrTfzmUfTYxApBx7TBiMLZJqQ\",\"joinUrl\":\"https:\\/\\/us02web.zoom.us\\/j\\/81215844933?pwd=ZUo0Ac37Kt8TOD2mwCmlSB3sGRFeia.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('13','pending','2025-11-29 10:30:00','2025-11-29 11:00:00','1',NULL,'1',NULL,'1',NULL,'','gq7snpob0272d7araej6437ls4',NULL,NULL,NULL,NULL,'{\"id\":82730861839,\"startUrl\":\"https:\\/\\/us02web.zoom.us\\/s\\/82730861839?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI4MjczMDg2MTgzOSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6ImVmOTIwN2IyZDNjMzQyMDY4Y2I5OWY2YmNkNDkwMzk4Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czAyIiwiZXhwIjoxNzYyNDYzMDc2LCJpYXQiOjE3NjI0NTU4NzYsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.jXWtSVpYUnpkUfRPlr8XyAf2R9OrAfzWACopEhk8ltM\",\"joinUrl\":\"https:\\/\\/us02web.zoom.us\\/j\\/82730861839?pwd=o6GxeYUDK1amPwHXbBBSZShJNvXqpg.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('15','approved','2025-11-22 20:30:00','2025-11-22 21:30:00','1','1','6',NULL,'6',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('16','pending','2025-12-07 07:00:00','2025-12-07 08:00:00','1','1','6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":77221189579,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/77221189579?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3NzIyMTE4OTU3OSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6ImY2OTc0ZTQzMzgzZDQxZTE5ZDZjZmNkYjFhN2NlZTY0Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY1MDA4NjY3LCJpYXQiOjE3NjUwMDE0NjcsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.hEl5GhLYhxt79BXBkQFR7D6xE3hTJJXlbwNi_vQsIsg\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/77221189579?pwd=EtkMIYhB2LXSxKg6jAMFtNXqOIfatj.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('17','pending','2025-12-07 12:30:00','2025-12-07 13:30:00','1',NULL,'6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('18','approved','2025-12-10 15:00:00','2025-12-10 16:00:00','1','0','6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":77857717150,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/77857717150?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3Nzg1NzcxNzE1MCIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6Ijk3MDYzYmUzNjhjYzQ0MzdhZjY5ZmY5Y2RlOTQxYmE1Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY1MjkwMjQxLCJpYXQiOjE3NjUyODMwNDEsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.DZX0FVMo2zEb5JMUje8HXXzfJ9yRsvT6Tvea-ftMTwA\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/77857717150?pwd=nsZfJoYFmpfb7DSPYNkrGPJcWXaboz.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('19','approved','2025-12-09 14:30:00','2025-12-09 15:30:00','1',NULL,'6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":78813128068,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/78813128068?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3ODgxMzEyODA2OCIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6ImU1YWU2MjIyYTg4ZDQ0MjVhMDMzMzlkNWM2ZWI2MGM5Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY1Mjk3MjM3LCJpYXQiOjE3NjUyOTAwMzcsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.poN80M8rYX4dckb3g61abuVDUvJvgCnualMl5ACsDeQ\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/78813128068?pwd=szev9SSOFagigvSU7ehz5vOLLbwM1M.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('20','approved','2025-12-09 20:30:00','2025-12-09 21:30:00','1','1','6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":71940449161,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/71940449161?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3MTk0MDQ0OTE2MSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjlhNTc2ZmJjZTM0NzQxNTc4ZDQzMjViZWYwZTNiYWE2Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY1MzA1NjYzLCJpYXQiOjE3NjUyOTg0NjMsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.sdiGLFLA9Bd7s_KxYDU-Zdd-CfCyH7EJWpeWvtoJgzE\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/71940449161?pwd=1UjGbpfbNIqNX68p0dSIibX5SCImjF.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('24','approved','2025-12-15 15:30:00','2025-12-15 16:30:00','1','1','6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":72418622185,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/72418622185?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3MjQxODYyMjE4NSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjE1MDNmZWM5MDYwYjQ5YTFhMTkzMTE1ZTRkMDRhZjdhIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY1NDM3NDU3LCJpYXQiOjE3NjU0MzAyNTcsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.WyyUtIaeXEU6Mraih4VjadL5lSWvLXhoFchsrY1nmDE\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/72418622185?pwd=qFh8tJkxb96ER2yBrAuFOb5b4VFfRc.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('25','approved','2025-12-16 21:00:00','2025-12-16 22:00:00','1','0','6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":73048064462,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/73048064462?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3MzA0ODA2NDQ2MiIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjVmM2EyMDJmOTA0YjRiN2E4ZWE3MzQ0NmQ2MmZkNWRjIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY1NDM4MDI2LCJpYXQiOjE3NjU0MzA4MjYsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.qdfwZb2GJ3zNtSbsVI9P6_0RPAFW6I4PYbgPO7jhRfQ\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/73048064462?pwd=Z0EhjTotA57ixzT3GtmdugzbjT28Bu.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('26','approved','2025-12-19 19:30:00','2025-12-19 20:30:00','1','1','6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":76490609165,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/76490609165?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3NjQ5MDYwOTE2NSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6ImY1MjFiMWE0MTA0ZDRjYjU4MzM1N2RiNzMzNjNhOTU4Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY1NDU1NTUzLCJpYXQiOjE3NjU0NDgzNTMsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.oWdL3bSUatz-ytBEAKoN0RIwSqsrkUEy9n_D04ZALug\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/76490609165?pwd=nPD5Q9BqUyuZ3pmpcU4IUvZSDxwNzg.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('27','pending','2025-12-19 15:30:00','2025-12-19 16:30:00','1',NULL,'6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('28','pending','2025-12-21 15:30:00','2025-12-21 16:30:00','1',NULL,'6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('30','pending','2025-12-12 14:30:00','2025-12-12 15:30:00','1',NULL,'6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('31','pending','2026-01-01 14:30:00','2026-01-01 15:30:00','1',NULL,'6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('32','pending','2026-01-01 17:00:00','2026-01-01 18:00:00','1',NULL,'6',NULL,'6','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('40','approved','2025-12-25 08:30:00','2025-12-25 09:30:00','1','0','6',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('41','approved','2025-12-30 08:30:00','2025-12-30 09:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('42','approved','2025-12-31 08:30:00','2025-12-31 09:00:00','1','0','1',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('43','approved','2026-01-13 09:30:00','2026-01-13 10:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('44','approved','2026-01-15 07:30:00','2026-01-15 08:30:00','1','0','1',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('45','approved','2026-01-21 09:30:00','2026-01-21 10:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('46','approved','2026-01-12 08:30:00','2026-01-12 09:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('47','approved','2026-01-22 19:30:00','2026-01-22 20:30:00','1',NULL,'6',NULL,'6',NULL,'',NULL,NULL,NULL,NULL,NULL,'{\"id\":72428401548,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/72428401548?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3MjQyODQwMTU0OCIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjQyY2IyY2EyMzQ3ZjQ3MjE5Zjg5OThiMWQ2YTgwYzFiIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY4Njc5Njc5LCJpYXQiOjE3Njg2NzI0NzksImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.AlhjZ8ZiG5J0Wepm4Lu2q1FaVLWG_de0gbWhEUMh9Zs\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/72428401548?pwd=A6aZkTFF36HZnbM5ALrsILhXrVgEcs.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('48','approved','2026-07-20 17:30:00','2026-07-20 18:00:00','1',NULL,'6',NULL,'6',NULL,'',NULL,NULL,NULL,NULL,NULL,'{\"id\":75643955002,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/75643955002?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3NTY0Mzk1NTAwMiIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjRlNWYyMTA4NmI4ODRlOWFhNmE3ZWFlMGNjYzhlNTA1Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY4OTM3NjQ5LCJpYXQiOjE3Njg5MzA0NDksImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.4WtKqi2DMSwiQMDb4OJe55crab1ssVFQj39dsEti_Gw\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/75643955002?pwd=tTbOrU49r4Vha0lHDIiXxVsd32JGPZ.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('49','approved','2026-10-19 22:30:00','2026-10-19 23:15:00','1',NULL,'6',NULL,'6',NULL,'',NULL,NULL,NULL,NULL,NULL,'{\"id\":71065482375,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/71065482375?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3MTA2NTQ4MjM3NSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjBjYWQ2MjQ3ZTRkMDRkNmY5MzQ1OTYxYmZmYWUyNGEwIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzY4OTM3ODQ2LCJpYXQiOjE3Njg5MzA2NDYsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.MffAeHo8yHT-yjm3ye_o3k9HXuDBDTpdW2BX9MrE4lI\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/71065482375?pwd=JsLrfXTN7jlmuTtXeTukQ0kej9ZdZT.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('50','pending','2026-02-24 07:30:00','2026-02-24 08:30:00','1',NULL,'1',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('51','approved','2026-02-19 06:00:00','2026-02-19 07:00:00','1','0','1',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('52','approved','2026-02-19 07:30:00','2026-02-19 08:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('53','approved','2026-02-20 09:30:00','2026-02-20 10:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('54','approved','2026-02-19 03:30:00','2026-02-19 05:00:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('55','approved','2026-02-24 06:00:00','2026-02-24 07:00:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('56','approved','2026-02-26 08:30:00','2026-02-26 09:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('57','approved','2026-02-23 04:00:00','2026-02-23 04:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('58','approved','2026-02-27 06:30:00','2026-02-27 07:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('59','approved','2026-02-26 07:30:00','2026-02-26 08:30:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('60','approved','2026-03-20 09:30:00','2026-03-20 10:30:00','1','0','1',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('61','approved','2026-03-25 05:30:00','2026-03-25 06:00:00','1',NULL,'6',NULL,'60',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('62','approved','2026-03-26 07:30:00','2026-03-26 08:30:00','1','1','1',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":74191462396,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/74191462396?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3NDE5MTQ2MjM5NiIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjQxZjQxZDg4NmZhMTQ2OGI4ZjMzZmNmNjMzYmFjN2Q2Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzc0MjcxMzYzLCJpYXQiOjE3NzQyNjQxNjMsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.GcbDMVJq0dOrulm2nhEKZY9-7QZe3RjPXTcPVQUbaj0\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/74191462396?pwd=RXgH0j1Mt0uI9pVxvzo0ZacN3Erfo3.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('63','approved','2026-03-27 05:00:00','2026-03-27 06:00:00','1','1','6',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":75690346235,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/75690346235?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3NTY5MDM0NjIzNSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjNkZTEwYTQzM2I3NjRlMWM4MGVmMjE2ZjdhY2ExODZiIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzc0MjcxNDc3LCJpYXQiOjE3NzQyNjQyNzcsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.WOdmqptznVL-Cokd8BeAPzmaUR8-AIl5em43aqUxIiQ\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/75690346235?pwd=q7xy6O8An4JHKupliJ3TnPan0jv37i.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('64','approved','2026-03-30 07:00:00','2026-03-30 08:00:00','1','1','6',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":78436416846,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/78436416846?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3ODQzNjQxNjg0NiIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjliYmI2YzU1YmIxMTRiZmE4NTIwNWY1OTI1N2M4MGQwIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzc0MjcyMDkyLCJpYXQiOjE3NzQyNjQ4OTIsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.MhmxsAJigRRbuetNXlxECXl7byXDaxKu0ndELAxUiwY\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/78436416846?pwd=HmfsmVbx8GuqKXXj3Nrce6497LCZ4n.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('65','approved','2026-03-31 05:30:00','2026-03-31 06:30:00','1','1','6',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":78090643749,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/78090643749?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3ODA5MDY0Mzc0OSIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6IjEwNzY0MjFjNWViMjRkYWQ4M2QzZTQ0YzNhY2IwOTIzIiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzc0MjcyNTAwLCJpYXQiOjE3NzQyNjUzMDAsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.81ikjUxsF4igyeGkmAf8FrjlSexhuqZjlp9hZ49Tnr4\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/78090643749?pwd=eTktpvovgofP7fd648DX95Jv4zNvCM.1\"}',NULL,NULL,'');
INSERT INTO `wp_amelia_appointments` (`id`,`status`,`bookingStart`,`bookingEnd`,`notifyParticipants`,`createPaymentLinks`,`serviceId`,`packageId`,`providerId`,`locationId`,`internalNotes`,`googleCalendarEventId`,`googleMeetUrl`,`outlookCalendarEventId`,`microsoftTeamsUrl`,`appleCalendarEventId`,`zoomMeeting`,`lessonSpace`,`parentId`,`error`) VALUES('66','approved','2026-03-31 07:30:00','2026-03-31 08:30:00','1','1','6',NULL,'60','1','',NULL,NULL,NULL,NULL,NULL,'{\"id\":77193126664,\"startUrl\":\"https:\\/\\/us04web.zoom.us\\/s\\/77193126664?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMiIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJ3ZWIiLCJjbHQiOjAsIm1udW0iOiI3NzE5MzEyNjY2NCIsImF1ZCI6ImNsaWVudHNtIiwidWlkIjoiN29pUEpmVmpSVlNCUkdsdGV3N3FCQSIsInppZCI6ImQ0YjZkMDk1YTdlMjRhOGJiZWM1NDNlYTZlNmY0ZTU4Iiwic2siOiIwIiwic3R5IjoxLCJ3Y2QiOiJ1czA0IiwiZXhwIjoxNzc0MjczMDI4LCJpYXQiOjE3NzQyNjU4MjgsImFpZCI6ImZSUjdPSm1MUXJpZzVhNWZIcWZqdkEiLCJjaWQiOiIifQ.EWy038-Yk_H74HSbQEd-ilTsIJKuW48dlbkMhEAmkAs\",\"joinUrl\":\"https:\\/\\/us04web.zoom.us\\/j\\/77193126664?pwd=bIIA42fXPawbrlGBW7ClNcowmrPaqy.1\"}',NULL,NULL,'');
-- rewind end page null
