-- rewind begin page null
CREATE TABLE `wp_amelia_customer_bookings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `appointmentId` int(11) DEFAULT NULL,
  `customerId` int(11) NOT NULL,
  `status` enum('approved','pending','canceled','rejected','no-show','waiting') DEFAULT NULL,
  `price` double NOT NULL,
  `tax` varchar(255) DEFAULT NULL,
  `persons` int(11) NOT NULL,
  `couponId` int(11) DEFAULT NULL,
  `token` varchar(10) DEFAULT NULL,
  `customFields` text DEFAULT NULL,
  `info` text DEFAULT NULL,
  `utcOffset` int(3) DEFAULT NULL,
  `aggregatedPrice` tinyint(1) DEFAULT 1,
  `packageCustomerServiceId` int(11) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `actionsCompleted` tinyint(1) DEFAULT NULL,
  `qrCodes` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=140 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('5','5','1','approved','0',NULL,'1',NULL,'5ac1144ce2',NULL,'{\"firstName\":\"SANYAM\",\"lastName\":\"JAIN\",\"phone\":\"+919588319998\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,'1800','2025-10-18 17:29:59','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('8',NULL,'1','pending','0',NULL,'1',NULL,'21f2b22ec0',NULL,'{\"firstName\":\"SANYAM\",\"lastName\":\"JAIN\",\"phone\":\"+919588319998\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,NULL,'2025-10-24 12:22:34','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('9',NULL,'1','canceled','200',NULL,'1',NULL,'5c1bc3ce12',NULL,'{\"firstName\":\"SANYAM\",\"lastName\":\"JAIN\",\"phone\":\"+919588319998\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,NULL,'2025-10-29 14:19:11','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('10','8','3','pending','0',NULL,'1',NULL,'aa08923f63',NULL,'{\"firstName\":\"SANYAM\",\"lastName\":\"JAIN\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,'1800','2025-10-31 20:22:24','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('12','10','3','pending','0',NULL,'1',NULL,'6a00f2cdb5',NULL,'{\"firstName\":\"Manjeet\",\"lastName\":\"Godara\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,'1800','2025-11-01 07:41:23','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('14','12','3','pending','0',NULL,'1',NULL,'0bb0afffdb',NULL,'{\"firstName\":\"Manjeet\",\"lastName\":\"Godara\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,'1800','2025-11-05 19:09:18','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('15','13','1','pending','0',NULL,'1',NULL,'d7db60a5de',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,'1800','2025-11-06 19:04:36','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('18','15','4','approved','200',NULL,'1',NULL,'633f552211','[]',NULL,NULL,'1',NULL,'3600','2025-11-22 18:27:54','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('19','16','7','pending','200',NULL,'1',NULL,'f42948c005','[]',NULL,NULL,'1',NULL,'3600','2025-12-06 06:11:07','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('20','17','7','pending','200',NULL,'1',NULL,'657a7e4a93',NULL,'{\"firstName\":\"Expert 1\",\"lastName\":\"-\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-06 06:22:05','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('21','18','3','approved','200',NULL,'1',NULL,'d26938a0fa','[]','{\"firstName\":\"Testing\",\"lastName\":\"09122025\",\"phone\":\"+919896881988\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-09 12:24:01','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('22','19','4','approved','200',NULL,'1',NULL,'33fd990d73',NULL,'{\"firstName\":\"Manjeet\",\"lastName\":\"Godara\",\"phone\":\"+919896881988\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-09 14:20:36','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('23','20','7','approved','200',NULL,'1',NULL,'091b2adbbf','[]',NULL,NULL,'1',NULL,'3600','2025-12-09 16:41:03','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('28','24','7','approved','200',NULL,'1',NULL,'a50ae14719','[]',NULL,NULL,'1',NULL,'3600','2025-12-11 05:17:37','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('29','25','7','approved','200',NULL,'1',NULL,'4b9ab65188','[]','{\"firstName\":\"Expert 1\",\"lastName\":\"-\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-11 05:25:49','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('30','26','7','approved','200',NULL,'1',NULL,'35de144fe7','[]',NULL,NULL,'1',NULL,'3600','2025-12-11 10:19:12','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('31','27','7','pending','200',NULL,'1',NULL,'fb792f0715',NULL,'{\"firstName\":\"Expert 1\",\"lastName\":\"-\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-11 10:36:22','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('32','28','7','pending','200',NULL,'1',NULL,'7146baa140',NULL,'{\"firstName\":\"Expert 1\",\"lastName\":\"-\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-11 10:55:32','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('34','30','7','pending','200',NULL,'1',NULL,'bc8244a49e',NULL,'{\"firstName\":\"Expert 1\",\"lastName\":\"-\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-11 15:14:24','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('35','31','7','pending','200',NULL,'1',NULL,'b941c6e16d',NULL,'{\"firstName\":\"Expert 1\",\"lastName\":\"-\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-11 15:17:50','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('36','32','7','pending','200',NULL,'1',NULL,'0710477bc9',NULL,'{\"firstName\":\"Expert 1\",\"lastName\":\"-\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,'3600','2025-12-11 15:32:00','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('37',NULL,'1','canceled','200',NULL,'1',NULL,'8c4dacafea',NULL,'{\"firstName\":\"SANYAM\",\"lastName\":\"JAIN\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-13 13:26:15','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('44','0','2','approved','500',NULL,'1',NULL,'052664db56',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('45','0','2','approved','500',NULL,'1',NULL,'37b7b10202',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('46','0','2','approved','500',NULL,'1',NULL,'a07910b5e9',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('47','0','2','approved','1800',NULL,'1',NULL,'29fb9b70a0',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('48','0','2','approved','1800',NULL,'1',NULL,'f376cf6329',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('49','0','2','approved','1800',NULL,'1',NULL,'3ef12e7545',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('50','0','2','approved','1801',NULL,'1',NULL,'88920eee7f',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('51','0','2','approved','1801',NULL,'1',NULL,'95ed84573a',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('53','0','2','approved','1900',NULL,'1',NULL,'9b046563de',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('54','0','2','approved','1900',NULL,'1',NULL,'b059d9cde9',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('55','0','2','approved','2001',NULL,'1',NULL,'b5a0ec0212',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('56','0','2','approved','2001',NULL,'1',NULL,'76c9730c17',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('57','0','2','approved','700',NULL,'1',NULL,'8f7845692f',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('58','0','2','approved','700',NULL,'1',NULL,'3c287c7aef',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('59','0','59','approved','900',NULL,'1',NULL,'24e5c88ae3',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('60','0','59','approved','900',NULL,'1',NULL,'6a1f34aeec',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('61','40','61','approved','1800',NULL,'1',NULL,'2615cfbbf2','[]',NULL,NULL,'1',NULL,'3600','2025-12-22 15:37:29','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('62','41','61','approved','1800',NULL,'1',NULL,'4ea6b96abb',NULL,NULL,NULL,'1',NULL,'3600','2025-12-22 19:01:28','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('63','42','12','approved','0',NULL,'1',NULL,'a5fcbf3d47','[]','{\"firstName\":\"sanyam\",\"lastName\":\"jain\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,'1800','2025-12-26 12:04:49','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('64',NULL,'12','approved','2000',NULL,'1',NULL,'84f790146e',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 10:40:15','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('65',NULL,'61','pending','2000',NULL,'1',NULL,'a8ca1f1b0d',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 14:26:24','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('66',NULL,'61','pending','2000',NULL,'1',NULL,'a850a35f4a',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 14:46:16','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('67',NULL,'61','pending','2000',NULL,'1',NULL,'80e6df5ceb',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 15:00:20','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('68',NULL,'61','pending','2000',NULL,'1',NULL,'4cd775eb0a',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 15:04:24','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('69',NULL,'61','pending','2000',NULL,'1',NULL,'c3b4be8a0e',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 15:11:12','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('70',NULL,'61','pending','2000',NULL,'1',NULL,'a1aa0321d8',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 15:15:06','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('71',NULL,'61','pending','2000',NULL,'1',NULL,'39ccdfb318',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 15:22:38','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('72',NULL,'61','pending','2000',NULL,'1',NULL,'5246f8408d',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 19:38:57','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('73',NULL,'61','pending','2000',NULL,'1',NULL,'fc6c6cac50',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 20:03:39','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('74',NULL,'61','pending','2000',NULL,'1',NULL,'bc4638d7d0',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 20:23:20','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('75',NULL,'61','pending','2000',NULL,'1',NULL,'e7c892d27c',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-27 20:41:18','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('76',NULL,'61','pending','2000',NULL,'1',NULL,'d2d008908e',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 07:45:05','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('77',NULL,'12','approved','1000',NULL,'1',NULL,'47ae72dc51',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 07:54:24','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('78',NULL,'61','canceled','1000',NULL,'1',NULL,'1b6f6fac26',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 08:39:20','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('79',NULL,'61','pending','1000',NULL,'1',NULL,'237c954e78',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 08:40:29','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('80',NULL,'61','pending','1000',NULL,'1',NULL,'0c7253f25f',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 08:44:05','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('81',NULL,'61','pending','1000',NULL,'1',NULL,'447bcf2ed0',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 16:27:45','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('82',NULL,'61','pending','1000',NULL,'1',NULL,'ffbdb5a021',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 16:37:50','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('83',NULL,'61','pending','1000',NULL,'1',NULL,'b15c5b0171',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 16:49:05','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('84',NULL,'61','pending','1000',NULL,'1',NULL,'1ab2505e31',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 16:55:08','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('85',NULL,'61','pending','1000',NULL,'1',NULL,'f3d5832a82',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 17:02:58','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('86',NULL,'61','pending','1000',NULL,'1',NULL,'bf704564c8',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 17:41:51','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('87',NULL,'61','pending','1000',NULL,'1',NULL,'b6a255f753',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2025-12-29 17:47:28','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('88','43','61','approved','1800',NULL,'1',NULL,'5ea5974661',NULL,NULL,NULL,'1',NULL,'3600','2026-01-07 12:47:56','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('89','44','12','approved','500',NULL,'1',NULL,'3dc00a69b2','[]','{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,'3600','2026-01-07 13:03:23','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('90','45','61','approved','1800',NULL,'1',NULL,'f5ea7acd86',NULL,NULL,NULL,'1',NULL,'3600','2026-01-08 12:05:13','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('91','46','61','approved','1800',NULL,'1',NULL,'738cf029cd',NULL,NULL,NULL,'1',NULL,'3600','2026-01-09 10:43:52','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('92','47','7','approved','1800',NULL,'1',NULL,'8c1fee4c4f',NULL,NULL,NULL,'1',NULL,'3600','2026-01-17 17:54:38','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('93','48','7','approved','1000',NULL,'1',NULL,'359657f9dc',NULL,NULL,NULL,'1',NULL,'1800','2026-01-20 17:34:08','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('94','49','7','approved','1800',NULL,'1',NULL,'9adae60deb',NULL,NULL,NULL,'1',NULL,'2700','2026-01-20 17:37:25','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('95',NULL,'61','canceled','1000',NULL,'1',NULL,'434e5cc88e',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2026-02-14 13:06:33','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('96','50','61','pending','500',NULL,'1',NULL,'9e234642ec',NULL,'{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,'3600','2026-02-14 13:11:45','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('97','51','61','approved','500',NULL,'1',NULL,'38662e4da5','[]','{\"firstName\":\"jain78790@gmail.com\",\"lastName\":\"Admin\",\"phone\":\"+919992431718\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,'3600','2026-02-14 13:13:47','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('98','52','61','approved','1800',NULL,'1',NULL,'a8f2d699a1',NULL,NULL,NULL,'1',NULL,'3600','2026-02-16 15:29:59','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('99','53','61','approved','1800',NULL,'1',NULL,'8c27bf9459',NULL,NULL,NULL,'1',NULL,'3600','2026-02-16 16:38:02','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('100','54','61','approved','2500',NULL,'1',NULL,'10f26c1596',NULL,NULL,NULL,'1',NULL,'5400','2026-02-18 07:17:08','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('101','55','61','approved','1800',NULL,'1',NULL,'dfd344dcac',NULL,NULL,NULL,'1',NULL,'3600','2026-02-19 14:12:15','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('102','56','61','approved','1800',NULL,'1',NULL,'26f4b133d3',NULL,NULL,NULL,'1',NULL,'3600','2026-02-20 12:56:11','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('103','57','61','approved','1000',NULL,'1',NULL,'836597d77f',NULL,NULL,NULL,'1',NULL,'1800','2026-02-20 14:20:29','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('104','58','61','approved','1800',NULL,'1',NULL,'a68010ad09',NULL,NULL,NULL,'1',NULL,'3600','2026-02-21 09:50:35','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('105','59','70','approved','1800',NULL,'1',NULL,'d6989751ea',NULL,NULL,NULL,'1',NULL,'3600','2026-02-21 16:27:10','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('106','60','12','approved','500',NULL,'1',NULL,'149b3d9336','[]','{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":\"+918903266557\",\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,'3600','2026-03-07 11:03:32','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('107',NULL,'12','approved','0',NULL,'1',NULL,'f420a1d7df',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":\"en_US\",\"timeZone\":\"Asia\\/Calcutta\",\"urlParams\":null}','330','1',NULL,NULL,'2026-03-07 11:55:26','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('108',NULL,'12','canceled','1000',NULL,'1',NULL,'4e0b0c046f',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,NULL,'2026-03-07 12:15:19','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('109',NULL,'12','approved','1000',NULL,'1',NULL,'0041ffd24a',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,NULL,'2026-03-07 12:20:01','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('110',NULL,'12','canceled','1000',NULL,'1',NULL,'1581bbf303',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-12 13:58:24','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('111',NULL,'12','canceled','1000',NULL,'1',NULL,'718c5c7ddd',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-12 16:30:55','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('112',NULL,'12','canceled','2000',NULL,'1',NULL,'4f63189f85',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-16 11:50:12','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('113',NULL,'12','canceled','1500',NULL,'1',NULL,'1dce57fb39',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-16 12:05:22','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('117',NULL,'12','canceled','1000',NULL,'1',NULL,'22ac693182',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,NULL,'2026-03-16 16:11:45','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('118','61','61','approved','1000',NULL,'1',NULL,'25a7d4310e',NULL,NULL,NULL,'1',NULL,'1800','2026-03-17 11:26:37','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('119',NULL,'12','approved','1500',NULL,'1',NULL,'6jCGge4nkg',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":\"\",\"locale\":\"en_US\"}',NULL,'1',NULL,NULL,'2026-03-17 17:35:24',NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('120',NULL,'12','approved','1000',NULL,'1',NULL,'oyMcqWebsM',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":\"\",\"locale\":\"en_US\"}',NULL,'1',NULL,NULL,'2026-03-17 17:36:56',NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('121',NULL,'12','approved','1000',NULL,'1',NULL,'mPk0IflXmX',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":\"\",\"locale\":\"en_US\"}',NULL,'1',NULL,NULL,'2026-03-17 21:05:10',NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('122',NULL,'12','canceled','1000',NULL,'1',NULL,'0880a7e1e3',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,NULL,'2026-03-17 16:03:20','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('123',NULL,'12','canceled','1000',NULL,'1',NULL,'e2d64d0a05',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'1',NULL,NULL,'2026-03-18 11:38:55','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('124',NULL,'12','canceled','1000',NULL,'1',NULL,'a45feeaf3a',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-18 12:51:52','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('125',NULL,'12','approved','0',NULL,'1',NULL,'3528ff3a13',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-18 13:38:41','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('128',NULL,'12','approved','0',NULL,'1',NULL,'0f8d590a4a',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-19 06:59:15','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('130',NULL,'12','approved','0',NULL,'1',NULL,'b4b7f274c6',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-19 15:16:59','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('131',NULL,'12','canceled','1000',NULL,'1',NULL,'d2d806d167',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-20 09:53:31','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('132',NULL,'12','canceled','1000',NULL,'1',NULL,'78e3847bc5',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-20 09:59:22','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('133',NULL,'12','canceled','100',NULL,'1',NULL,'0817eeb678',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":null,\"locale\":null,\"timeZone\":null,\"urlParams\":null}',NULL,'0',NULL,NULL,'2026-03-20 10:02:18','0',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('134',NULL,'12','approved','100',NULL,'1',NULL,'3PcmTdIwMJ',NULL,'{\"firstName\":\"Sanyam\",\"lastName\":\"Jain\",\"phone\":\"\",\"locale\":\"en_US\"}',NULL,'1',NULL,NULL,'2026-03-20 15:33:04',NULL,NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('135','62','12','approved','500',NULL,'1',NULL,'ac47855d71','[]',NULL,NULL,'1',NULL,'3600','2026-03-23 11:09:22','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('136','63','61','approved','1800',NULL,'1',NULL,'a2f3a566b6','[]',NULL,NULL,'1',NULL,'3600','2026-03-23 11:11:17','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('137','64','12','approved','1800',NULL,'1',NULL,'b735224579','[]',NULL,NULL,'1',NULL,'3600','2026-03-23 11:21:32','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('138','65','61','approved','1800',NULL,'1',NULL,'99d438220a','[]',NULL,NULL,'1',NULL,'3600','2026-03-23 11:28:19','1',NULL);
INSERT INTO `wp_amelia_customer_bookings` (`id`,`appointmentId`,`customerId`,`status`,`price`,`tax`,`persons`,`couponId`,`token`,`customFields`,`info`,`utcOffset`,`aggregatedPrice`,`packageCustomerServiceId`,`duration`,`created`,`actionsCompleted`,`qrCodes`) VALUES('139','66','61','approved','1800',NULL,'1',NULL,'fab504e62e','[]',NULL,NULL,'1',NULL,'3600','2026-03-23 11:37:07','1',NULL);
-- rewind end page null
