-- rewind begin page null
CREATE TABLE `wp_amelia_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parentId` bigint(20) DEFAULT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `status` enum('approved','pending','canceled','rejected') NOT NULL,
  `bookingOpens` datetime DEFAULT NULL,
  `bookingCloses` datetime DEFAULT NULL,
  `bookingOpensRec` enum('same','calculate') DEFAULT 'same',
  `bookingClosesRec` enum('same','calculate') DEFAULT 'same',
  `ticketRangeRec` enum('same','calculate') DEFAULT 'calculate',
  `recurringCycle` enum('daily','weekly','monthly','yearly') DEFAULT NULL,
  `recurringOrder` int(11) DEFAULT NULL,
  `recurringInterval` int(11) DEFAULT 1,
  `recurringMonthly` enum('each','on') DEFAULT 'each',
  `monthlyDate` datetime DEFAULT NULL,
  `monthlyOnRepeat` enum('first','second','third','fourth','fifth','last') DEFAULT NULL,
  `monthlyOnDay` enum('monday','tuesday','wednesday','thursday','friday','saturday','sunday') DEFAULT NULL,
  `recurringUntil` datetime DEFAULT NULL,
  `maxCapacity` int(11) NOT NULL,
  `maxCustomCapacity` int(11) DEFAULT NULL,
  `maxExtraPeople` int(11) DEFAULT NULL,
  `price` double NOT NULL,
  `locationId` bigint(20) DEFAULT NULL,
  `customLocation` varchar(255) DEFAULT NULL,
  `description` mediumtext DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `show` tinyint(1) NOT NULL DEFAULT 1,
  `notifyParticipants` tinyint(1) NOT NULL,
  `created` datetime NOT NULL,
  `settings` mediumtext DEFAULT NULL,
  `zoomUserId` varchar(255) DEFAULT NULL,
  `bringingAnyone` tinyint(1) DEFAULT 1,
  `bookMultipleTimes` tinyint(1) DEFAULT 1,
  `translations` text DEFAULT NULL,
  `depositPayment` enum('disabled','fixed','percentage') DEFAULT 'disabled',
  `depositPerPerson` tinyint(1) DEFAULT 1,
  `fullPayment` tinyint(1) DEFAULT 0,
  `deposit` double DEFAULT 0,
  `customPricing` tinyint(1) DEFAULT 0,
  `organizerId` bigint(20) DEFAULT NULL,
  `closeAfterMin` int(11) DEFAULT NULL,
  `closeAfterMinBookings` tinyint(1) DEFAULT 0,
  `aggregatedPrice` tinyint(1) DEFAULT 1,
  `error` mediumtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('1',NULL,'Tutorial','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'7',NULL,NULL,'200',NULL,'jain78790@gmail.com','','#1788FB','1','1','2025-10-15 23:53:57','{\"payments\":{\"paymentLinks\":{\"enabled\":false,\"changeBookingStatus\":false,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0','1',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('2',NULL,'Webinar','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4',NULL,NULL,'200',NULL,NULL,'','#1788FB','1','1','2025-11-14 16:46:59','{\"payments\":{\"paymentLinks\":{\"enabled\":false,\"changeBookingStatus\":false,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0',NULL,NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('3',NULL,'Webinar','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'60',NULL,NULL,'100',NULL,NULL,'','#1788FB','1','1','2025-11-14 17:06:44','{\"payments\":{\"paymentLinks\":{\"enabled\":false,\"changeBookingStatus\":false,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0',NULL,NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('4',NULL,'Availibility','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'0',NULL,NULL,'','#1788FB','1','1','2025-12-09 16:55:26','{\"payments\":{\"paymentLinks\":{\"enabled\":false,\"changeBookingStatus\":false,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0',NULL,NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('5',NULL,'Web1','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'0','1',NULL,'','#1788FB','1','1','2025-12-10 13:06:15','{\"payments\":{\"paymentLinks\":{\"enabled\":false,\"changeBookingStatus\":false,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0',NULL,NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('6',NULL,'Webinar 2','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'10',NULL,NULL,'200','1',NULL,'','#1788FB','1','1','2025-12-13 18:53:59','{\"payments\":{\"paymentLinks\":{\"enabled\":false,\"changeBookingStatus\":false,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0',NULL,NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('7',NULL,'Web3','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'0','1',NULL,'','#1788FB','1','1','2025-12-15 16:49:06','{\"payments\":{\"paymentLinks\":{\"enabled\":false,\"changeBookingStatus\":false,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0',NULL,NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('8',NULL,'Cardio','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100',NULL,NULL,'2000','1',NULL,'','#1788FB','1','1','2025-12-27 16:05:01','{\"payments\":{\"paymentLinks\":{\"enabled\":false,\"changeBookingStatus\":false,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','0',NULL,'disabled','1','0','0','0','60',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('9',NULL,'Neuro','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100',NULL,NULL,'1000','1',NULL,'','#1788FB','1','1','2025-12-29 13:21:17','{\"payments\":{\"paymentLinks\":{\"enabled\":true,\"changeBookingStatus\":true,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0','60',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('10',NULL,'Cardio Event','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'0','1',NULL,'','#1788FB','1','1','2026-01-21 16:53:46','{\"payments\":{\"paymentLinks\":{\"enabled\":true,\"changeBookingStatus\":true,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0','60',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('11',NULL,'testing event','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'50',NULL,NULL,'1000','1',NULL,'','#1788FB','1','1','2026-02-14 18:34:58','{\"payments\":{\"onSite\":false,\"paymentLinks\":{\"enabled\":true,\"changeBookingStatus\":true,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','0',NULL,'disabled','1','0','0','0','60',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('12',NULL,'Test Event','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'0','1',NULL,'','#1788FB','1','1','2026-03-07 15:52:36','{\"payments\":{\"paymentLinks\":{\"enabled\":true,\"changeBookingStatus\":true,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0','60',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('13',NULL,'Math Tutorial','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'1000','1',NULL,'','#1788FB','1','1','2026-03-07 17:44:30','{\"payments\":{\"paymentLinks\":{\"enabled\":true,\"changeBookingStatus\":true,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0','60',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('14',NULL,'Chem Tutorial','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'3',NULL,NULL,'1000','1',NULL,'','#1788FB','1','1','2026-03-07 17:49:50','{\"payments\":{\"paymentLinks\":{\"enabled\":true,\"changeBookingStatus\":true,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0','60',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('15',NULL,'Test Consultation','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'10',NULL,NULL,'1500',NULL,NULL,'Testing','#1788FB','1','1','2026-03-12 17:24:25',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('16',NULL,'Test Consultation 2','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'10',NULL,NULL,'1000',NULL,NULL,'Test','#1788FB','1','1','2026-03-12 17:32:13',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('17',NULL,'Test Consultation 3','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'8',NULL,NULL,'1000',NULL,NULL,'Test 3','#1788FB','1','1','2026-03-12 18:29:09',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('18',NULL,'New Webinar','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'10',NULL,NULL,'1000',NULL,NULL,'Testing Webinar','#1788FB','1','1','2026-03-12 21:56:33',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('19',NULL,'Check payment Event','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'3',NULL,NULL,'1000','1',NULL,'','#1788FB','1','1','2026-03-16 17:40:21','{\"payments\":{\"paymentLinks\":{\"enabled\":true,\"changeBookingStatus\":true,\"redirectUrl\":null}},\"general\":{\"minimumTimeRequirementPriorToCanceling\":null,\"redirectUrlAfterAppointment\":null},\"zoom\":{\"enabled\":true},\"lessonSpace\":{\"enabled\":false},\"googleMeet\":{\"enabled\":false},\"microsoftTeams\":{\"enabled\":false},\"waitingList\":{\"enabled\":false,\"addingMethod\":\"Manually\",\"maxCapacity\":1,\"maxExtraPeopleEnabled\":false,\"maxExtraPeople\":0}}','7oiPJfVjRVSBRGltew7qBA','1','1',NULL,'disabled','1','0','0','0','60',NULL,'0','1','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('20',NULL,'Time Test','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2',NULL,NULL,'0',NULL,NULL,'Time','#1788FB','1','1','2026-03-18 19:03:58',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('21',NULL,'Time Test 2','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'100',NULL,NULL,'-','#1788FB','1','1','2026-03-18 19:29:28',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('22',NULL,'Time Test 3','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,'0',NULL,NULL,'1','#1788FB','1','1','2026-03-18 19:53:15',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('23',NULL,'Free Test','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100',NULL,NULL,'0',NULL,NULL,'Free','#1788FB','1','1','2026-03-19 20:26:41',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
INSERT INTO `wp_amelia_events` (`id`,`parentId`,`name`,`status`,`bookingOpens`,`bookingCloses`,`bookingOpensRec`,`bookingClosesRec`,`ticketRangeRec`,`recurringCycle`,`recurringOrder`,`recurringInterval`,`recurringMonthly`,`monthlyDate`,`monthlyOnRepeat`,`monthlyOnDay`,`recurringUntil`,`maxCapacity`,`maxCustomCapacity`,`maxExtraPeople`,`price`,`locationId`,`customLocation`,`description`,`color`,`show`,`notifyParticipants`,`created`,`settings`,`zoomUserId`,`bringingAnyone`,`bookMultipleTimes`,`translations`,`depositPayment`,`depositPerPerson`,`fullPayment`,`deposit`,`customPricing`,`organizerId`,`closeAfterMin`,`closeAfterMinBookings`,`aggregatedPrice`,`error`) VALUES('24',NULL,'Final Test','approved',NULL,NULL,'same','same','calculate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2',NULL,NULL,'1000',NULL,NULL,'Test','#1788FB','1','1','2026-03-20 15:41:22',NULL,'sanyam.jain@inditech.co.in','0','0',NULL,'disabled','0','0','0','0','60',NULL,'0','0','');
-- rewind end page null
