-- rewind begin page null
CREATE TABLE `wp_fs_saved_replies` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `mailbox_id` bigint(20) unsigned DEFAULT NULL,
  `product_id` bigint(20) unsigned DEFAULT NULL,
  `title` varchar(192) DEFAULT NULL,
  `content` longtext DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('1','1',NULL,'0','Login/Password reset','<blockquote>\n<p>Hi {{first_name}},</p>\n<p>Please reset your password from <strong>/my-account</strong> using the <strong>“Lost your password?”</strong> link. If you see “link expired”, fully log out and retry in a private/incognito window. If it still fails, reply with your browser + device and we’ll help.</p>\n</blockquote>\n<p><!-- notionvc: e3f73d0f-2f5f-4af3-b086-f51535b5852f --></p>','2025-10-23 13:30:19','2025-10-23 13:30:19');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('2','1',NULL,'0','Where is my webinar link?','<p>Your webinar’s Join link is in /my-events and in the email confirmation (check spam too). It also appears in the attached calendar .ics. If the time changes, /my-events updates automatically.</p>','2025-10-23 13:30:39','2025-10-23 13:30:39');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('3','1',NULL,'0','Can I get a webinar recording?','<p>Recordings, when available, are published in Webinar Archives within 48–72 hours. We’ll email you once it’s listed.</p>','2025-10-23 13:30:58','2025-10-23 13:30:58');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('4','1',NULL,'0','Tutorial booking – how it works','<p>Choose a time on the expert’s calendar, complete checkout, and you’ll receive a confirmation with a calendar .ics. You can manage or reschedule from /my-tutorials.</p>','2025-10-23 13:31:41','2025-10-23 13:31:41');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('5','1',NULL,'0','Reschedule/Cancellation policy (tutorials)','<p>You can reschedule from /my-tutorials. If an expert cancels, you’ll be fully refunded. For learner‑initiated cancellations, our policy applies as shown at checkout.</p>','2025-10-23 13:31:55','2025-10-23 13:31:55');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('6','1',NULL,'0','College class access','<p>College sessions are restricted to student lists sent by your college. Please confirm you’re on the list; your coordinator shares the access link and time. If you missed it, we’ll send the recap email (if enabled).</p>','2025-10-23 13:32:06','2025-10-23 13:32:06');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('7','1',NULL,'0','Payments/Invoices','<p>You can download invoices from /my-account → Orders. If a payment failed, retry once. If you see a duplicate charge, reply here and we’ll verify and refund if needed.</p>','2025-10-23 13:32:20','2025-10-23 13:32:20');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('8','1',NULL,'0','Certificates','<p>Certificates are generated after course completion and emailed to you. If you didn’t receive one, confirm the course shows as Completed and reply here.</p>','2025-10-23 13:32:32','2025-10-23 13:32:32');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('9','1',NULL,'0','Recorded lectures / courses access','<p>If access is missing, your subscription may have expired or the item is excluded from your plan. You can renew at checkout or purchase the item individually.</p>','2025-10-23 13:32:49','2025-10-23 13:32:49');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('10','1',NULL,'0','Data deletion / privacy','<p>We can delete your account or export your data upon request. Please confirm from the account email and we’ll proceed.</p>','2025-10-23 13:33:06','2025-10-23 13:33:06');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('11',NULL,NULL,NULL,'Webinar join link','Your webinar Join link is in /my-events and in your email confirmation. The .ics calendar also includes it. If the schedule changes, /my-events updates automatically.','2025-10-23 14:22:07','2025-10-23 14:22:07');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('12',NULL,NULL,NULL,'Webinar recording availability','Recordings (when allowed) appear in Webinar Archives within 48�72h. We\'ll notify you once published.','2025-10-23 14:22:07','2025-10-23 14:22:07');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('13',NULL,NULL,NULL,'How to book a tutorial','Pick a slot on the expert calendar, complete checkout, and manage from /my-tutorials. You will receive an email + .ics file.','2025-10-23 14:22:07','2025-10-23 14:22:07');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('14',NULL,NULL,NULL,'Reschedule/cancellation (tutorials)','You can reschedule from /my-tutorials. If an expert cancels you get a full refund. Learner-initiated cancellations follow the policy shown at checkout.','2025-10-23 14:22:07','2025-10-23 14:22:07');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('15',NULL,NULL,NULL,'Payments & invoices','Invoices/receipts live under /my-account ? Orders. If a payment failed, retry once. For duplicate charges, reply and we\'ll verify/refund.','2025-10-23 14:22:07','2025-10-23 14:22:07');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('16',NULL,NULL,NULL,'Recorded content access','If access is missing, your subscription may have expired or the item is excluded. Renew or purchase individually, then refresh your page.','2025-10-23 14:22:07','2025-10-23 14:22:07');
INSERT INTO `wp_fs_saved_replies` (`id`,`created_by`,`mailbox_id`,`product_id`,`title`,`content`,`created_at`,`updated_at`) VALUES('17',NULL,NULL,NULL,'Data deletion/privacy','We can delete/export your data upon request. Please confirm from the account email address and we\'ll proceed.','2025-10-23 14:22:07','2025-10-23 14:22:07');
-- rewind end page null
