-- rewind begin page null
CREATE TABLE `wp_tutor_orders` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint(20) unsigned DEFAULT 0,
  `transaction_id` varchar(255) DEFAULT NULL COMMENT 'Transaction id from payment gateway',
  `user_id` bigint(20) unsigned NOT NULL,
  `order_type` varchar(50) NOT NULL,
  `order_status` varchar(50) NOT NULL,
  `payment_status` varchar(50) NOT NULL,
  `subtotal_price` decimal(13,2) NOT NULL,
  `pre_tax_price` decimal(13,2) NOT NULL,
  `tax_type` varchar(50) DEFAULT NULL,
  `tax_rate` decimal(13,2) DEFAULT NULL COMMENT 'Tax percentage',
  `tax_amount` decimal(13,2) DEFAULT NULL,
  `total_price` decimal(13,2) NOT NULL,
  `net_payment` decimal(13,2) NOT NULL,
  `coupon_code` varchar(255) DEFAULT NULL,
  `coupon_amount` decimal(13,2) DEFAULT NULL,
  `discount_type` enum('percentage','flat') DEFAULT NULL,
  `discount_amount` decimal(13,2) DEFAULT NULL,
  `discount_reason` text DEFAULT NULL,
  `fees` decimal(13,2) DEFAULT NULL,
  `earnings` decimal(13,2) DEFAULT NULL,
  `refund_amount` decimal(13,2) DEFAULT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `payment_payloads` longtext DEFAULT NULL,
  `note` text DEFAULT NULL,
  `created_at_gmt` datetime NOT NULL,
  `created_by` bigint(20) unsigned NOT NULL,
  `updated_at_gmt` datetime DEFAULT NULL,
  `updated_by` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `order_type` (`order_type`),
  KEY `payment_status` (`payment_status`),
  KEY `order_status` (`order_status`),
  KEY `transaction_id` (`transaction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
-- rewind end page null
