-- rewind begin page null
CREATE TABLE `wp_wpda_publisher` (
  `pub_id` mediumint(9) NOT NULL AUTO_INCREMENT,
  `pub_name` varchar(100) NOT NULL,
  `pub_data_source` enum('Table','Query','CPT') DEFAULT 'Table',
  `pub_schema_name` varchar(64) NOT NULL DEFAULT '',
  `pub_table_name` varchar(64) NOT NULL,
  `pub_column_names` varchar(4096) DEFAULT '*',
  `pub_cpt` varchar(20) DEFAULT NULL,
  `pub_cpt_fields` text DEFAULT NULL,
  `pub_cpt_query` text DEFAULT NULL,
  `pub_cpt_format` text DEFAULT NULL,
  `pub_format` text DEFAULT NULL,
  `pub_query` text DEFAULT NULL,
  `pub_sort_icons` enum('default','none') DEFAULT NULL,
  `pub_styles` set('default','stripe','hover','order-column','row-border','compact','cell-border') DEFAULT 'default',
  `pub_style_premium` enum('Yes','No') DEFAULT 'No',
  `pub_style_user` varchar(50) DEFAULT NULL,
  `pub_style_color` varchar(50) DEFAULT 'default',
  `pub_style_space` tinyint(2) unsigned DEFAULT 10,
  `pub_style_corner` tinyint(2) unsigned DEFAULT 0,
  `pub_style_modal_width` tinyint(2) unsigned DEFAULT 80,
  `pub_responsive` enum('Yes','No') DEFAULT NULL,
  `pub_responsive_popup_title` varchar(50) DEFAULT NULL,
  `pub_responsive_cols` int(10) unsigned DEFAULT 0,
  `pub_responsive_type` enum('Modal','Collapsed','Expanded') DEFAULT NULL,
  `pub_responsive_modal_hyperlinks` enum('If not listed','Never','Always') DEFAULT NULL,
  `pub_responsive_icon` enum('Yes','No') DEFAULT NULL,
  `pub_flat_scrollx` enum('Yes','No') DEFAULT NULL,
  `pub_show_advanced_settings` tinyint(1) DEFAULT NULL,
  `pub_default_where` varchar(2000) DEFAULT '',
  `pub_default_orderby` varchar(100) DEFAULT '',
  `pub_table_options_searching` char(3) DEFAULT 'on',
  `pub_table_options_ordering` char(3) DEFAULT 'on',
  `pub_table_options_paging` char(3) DEFAULT 'on',
  `pub_table_options_serverside` char(3) DEFAULT 'on',
  `pub_table_options_nl2br` char(3) DEFAULT NULL,
  `pub_table_options_advanced` text DEFAULT NULL,
  `pub_extentions` varchar(2000) DEFAULT '',
  PRIMARY KEY (`pub_id`),
  UNIQUE KEY `pub_name` (`pub_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
-- rewind end page null
