-- rewind begin page null
CREATE TABLE `wp_wc_admin_note_actions` (
  `action_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `note_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `label` varchar(255) NOT NULL,
  `query` longtext NOT NULL,
  `status` varchar(255) NOT NULL,
  `actioned_text` varchar(255) NOT NULL,
  `nonce_action` varchar(255) DEFAULT NULL,
  `nonce_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`action_id`),
  KEY `note_id` (`note_id`)
) ENGINE=InnoDB AUTO_INCREMENT=14427 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('1','1','notify-refund-returns-page','Edit page','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/post.php?post=117&action=edit','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('1003','55','learn-more','Learn more','https://woocommerce.com/posts/pre-launch-checklist-the-essentials/?utm_source=inbox&utm_medium=product','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('1159','57','day-after-first-product','Learn more','https://woocommerce.com/document/woocommerce-customizer/?utm_source=inbox&utm_medium=product','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('1160','58','learn-more','Learn more','https://woocommerce.com/mobile/?utm_medium=product','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('1392','59','jetpack-backup-woocommerce','Get backups','https://jetpack.com/upgrade/backup-woocommerce/?utm_source=inbox&#038;utm_medium=automattic_referred&#038;utm_campaign=jp_backup_to_woo','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('2950','60','pinterest_q4_2025','Get started with Pinterest','https://woocommerce.com/products/pinterest-for-woocommerce/?utm_source=inbox_note&utm_medium=product&utm_campaign=pinterest_q4_2025','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('4425','63','paypaladvantage_q4_2025','Activate PayPal Today','https://woocommerce.com/products/woocommerce-paypal-payments/?utm_source=inbox_note&utm_medium=product&utm_campaign=paypaladvantage_q4_2025','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('4815','64','reddit_q4_2025','Get started with Reddit','https://woocommerce.com/products/reddit/?utm_source=inbox_note&utm_medium=product&utm_campaign=reddit_q4_2025','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('4973','68','view-report','View report','?page=wc-admin&path=/analytics/revenue&period=custom&compare=previous_year&after=2025-11-21&before=2025-11-21','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('5363','67','bfcm_general_sale_q4_2025','Boost your store for less','https://woocommerce.com/products/?utm_source=inbox_note&utm_medium=product&utm_campaign=bfcm_general_sale_q4_2025','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('7091','70','Google_q4_2025','Update Now','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('7647','71','holiday_shipping_deadlines_WCST_2025_button','Learn More','https://woocommerce.com/document/woocommerce-shipping/?utm_source=inbox_note&utm_medium=product&utm_campaign=holiday_shipping_deadlines_WCST_2025_button#2025-holiday-shipping-deadlines','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('7648','72','holiday_shipping_deadlines_WCS_2025_button','Learn More','https://woocommerce.com/document/woocommerce-shipping/?utm_source=inbox_note&utm_medium=product&utm_campaign=holiday_shipping_deadlines_WCS_2025_button#2025-holiday-shipping-deadlines','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('8688','75','review-orders','Review your orders','?page=wc-admin&path=/analytics/orders','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('8848','73','snap_q4_2025','Get started with Snapchat','https://woocommerce.com/products/snapchat/?utm_source=inbox_note&utm_medium=product&utm_campaign=snap_q4_2025','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('8851','74','stripe_agenticcommerce_3PDs_q4_2025_click','Get Stripe for WooCommerce','https://woocommerce.com/products/stripe/?utm_source=inbox_note&utm_medium=product&utm_campaign=stripe_agenticcommerce_3PDs_q4_2025_click','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('9172','76','WC10.4.3-security-update-12-22-2025','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php?','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('9327','53','payson-retirement-2025','Explore alternative payment methods','https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/?categoryIds=28680&collections=product&page=1&country=Sweden&utm_source=inbox_note&utm_medium=product&utm_campaign=payson-retirement-2025','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('9957','77','downloads-sub-Jan2026-RIN-button','Learn More','https://woocommerce.com/document/subscriptions/store-manager-guide/?utm_source=inbox_note&utm_medium=product&utm_campaign=downloads-sub-Jan2026-RIN-button#downloads-settings','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('9958','78','learn-more','Learn more','https://woocommerce.com/mobile/?utm_source=inbox&utm_medium=product','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('10278','80','USPS API Migration_RIN_button_Jan2026','View Migration Guide','https://woocommerce.com/document/usps-shipping-method/?utm_source=inbox_note&utm_medium=product&utm_campaign=USPS%20API%20Migration_RIN_button_Jan2026#connecting-the-api','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('11087','81','existing_square_bitcoin_promotion_q1_2026_click','Learn about bitcoin payments','https://woocommerce.com/posts/square-bitcoin-launch?utm_source=inbox_note&utm_medium=product&utm_campaign=existing_square_bitcoin_promotion_q1_2026_click','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('11088','82','prospects_square_bitcoin_promotion_q1_2026_click','Get started with Square','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/https://woocommerce.com/products/square/?utm_source=inbox_note&utm_medium=product&utm_campaign=prospects_square_bitcoin_promotion_q1_2026_click','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('11165','69','setup-instructions','Setup Instructions','https://woocommerce.com/document/woocommerce-paypal-payments/fraud-and-disputes/?utm_source=inbox_note&utm_medium=product&utm_campaign=setup-instructions#section-4','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('11166','69','activate-now','Activate Now','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=integration&section=ppcp-recaptcha','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('11403','83','scheduled-updates-enable','Enable','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-admin','actioned','Scheduled updates enabled',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('11797','84','reddit_q1_2026','Get started with Reddit for WooCommerce','https://woocommerce.com/products/reddit/?utm_source=inbox_note&utm_medium=product&utm_campaign=reddit_q1_2026','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('12192','85','Googleupdate_q1_2026','Get started with Google','https://woocommerce.com/products/google-listings-and-ads/?utm_source=inbox_note&utm_medium=product&utm_campaign=Googleupdate_q1_2026','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('12972','79','setup-instructions','Setup Instructions','https://woocommerce.com/document/woocommerce-paypal-payments/fraud-and-disputes/?utm_source=inbox_note&utm_medium=product&utm_campaign=setup-instructions#section-4','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('12973','79','activate-now','Activate Now','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=integration&section=ppcp-recaptcha','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('12974','86','Mailchimp-API-maintenance-feb-2026','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('13588','87','RIN-WC-Security-Update-admin-update-March-2026','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php?','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('13818','88','USPS_Scan_Form_Mar2026_button','Learn More','https://woocommerce.com/document/woocommerce-shipping/?utm_source=inbox_note&utm_medium=product&utm_campaign=USPS_Scan_Form_Mar2026_button#USPS-scan-forms','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14351','2','learn-more','Learn more','https://woocommerce.com/posts/ecommerce-shipping-solutions-guide/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14352','3','optimizing-the-checkout-flow','Learn more','https://woocommerce.com/posts/optimizing-woocommerce-checkout?utm_source=inbox_note&utm_medium=product&utm_campaign=optimizing-the-checkout-flow','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14353','4','qualitative-feedback-from-new-users','Share feedback','https://automattic.survey.fm/woopayments-new-user-feedback','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14354','5','share-feedback','Share feedback','http://automattic.survey.fm/paypal-feedback','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14355','6','get-started','Get started','https://woocommerce.com/products/google-listings-and-ads?utm_source=inbox_note&utm_medium=product&utm_campaign=get-started','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14356','7','update-wc-subscriptions-3-0-15','View latest version','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/&page=wc-addons&section=helper','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14357','8','update-wc-core-5-4-0','How to update WooCommerce','https://docs.woocommerce.com/document/how-to-update-woocommerce/','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14358','11','ppxo-pps-install-paypal-payments-1','View upgrade guide','https://docs.woocommerce.com/document/woocommerce-paypal-payments/paypal-payments-upgrade-guide/','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14359','12','ppxo-pps-install-paypal-payments-2','View upgrade guide','https://docs.woocommerce.com/document/woocommerce-paypal-payments/paypal-payments-upgrade-guide/','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14360','13','learn-more','Learn more','https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14361','13','dismiss','Dismiss','','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14362','14','learn-more','Learn more','https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14363','14','dismiss','Dismiss','','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14364','15','learn-more','Learn more','https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14365','15','dismiss','Dismiss','','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14366','16','learn-more','Learn more','https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14367','16','dismiss','Dismiss','','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14368','17','share-feedback','Share feedback','https://automattic.survey.fm/store-management','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14369','18','learn-more','Learn more','https://developer.woocommerce.com/2022/03/10/woocommerce-3-5-10-6-3-1-security-releases/','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14370','18','woocommerce-core-paypal-march-2022-dismiss','Dismiss','','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14371','19','learn-more','Learn more','https://developer.woocommerce.com/2022/03/10/woocommerce-3-5-10-6-3-1-security-releases/','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14372','19','dismiss','Dismiss','','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14373','20','pinterest_03_2022_update','Update Instructions','https://woocommerce.com/document/pinterest-for-woocommerce/?utm_source=inbox_note&utm_medium=product&utm_campaign=pinterest_03_2022_update#section-3','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14374','21','store_setup_survey_survey_q2_2022_share_your_thoughts','Tell us how it’s going','https://automattic.survey.fm/store-setup-survey-2022','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14375','22','needs-update-eway-payment-gateway-rin-action-button-2022-12-20','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14376','22','needs-update-eway-payment-gateway-rin-dismiss-button-2022-12-20','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14377','23','updated-eway-payment-gateway-rin-action-button-2022-12-20','See all updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14378','23','updated-eway-payment-gateway-rin-dismiss-button-2022-12-20','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14379','24','share-navigation-survey-feedback','Share feedback','https://automattic.survey.fm/new-ecommerce-plan-navigation','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14380','25','woopay-beta-merchantrecruitment-activate-04MAY23','Activate WooPay','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14381','25','woopay-beta-merchantrecruitment-activate-learnmore-04MAY23','Learn More','https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-activate-learnmore-04MAY23','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14382','26','woocommerce-wcpay-march-2023-update-needed-button','See Blog Post','https://developer.woocommerce.com/2023/03/23/critical-vulnerability-detected-in-woocommerce-payments-what-you-need-to-know','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14383','26','woocommerce-wcpay-march-2023-update-needed-dismiss-button','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14384','27','tap_to_pay_iphone_q2_2023_no_wcpay','Simplify my payments','https://woocommerce.com/products/woocommerce-payments/?utm_source=inbox_note&utm_medium=product&utm_campaign=tap_to_pay_iphone_q2_2023_no_wcpay','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14385','28','extension-settings','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14386','28','dismiss','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14387','29','woopay-beta-merchantrecruitment-update-WCPay-04MAY23','Update WooCommerce Payments','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14388','29','woopay-beta-merchantrecruitment-update-activate-04MAY23','Activate WooPay','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14389','30','woopay-beta-existingmerchants-noaction-documentation-27APR23','Documentation','https://woocommerce.com/document/woopay-merchant-documentation/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-existingmerchants-noaction-documentation-27APR23','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14390','31','woopay-beta-existingmerchants-update-WCPay-27APR23','Update WooCommerce Payments','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14391','32','woopay-beta-merchantrecruitment-short-activate-04MAY23','Activate WooPay','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14392','32','woopay-beta-merchantrecruitment-short-activate-learnmore-04MAY23','Learn More','https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-short-activate-learnmore-04MAY23','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14393','33','woopay-beta-merchantrecruitment-short-update-WCPay-04MAY23','Update WooCommerce Payments','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14394','33','woopay-beta-merchantrecruitment-short-update-activate-04MAY23','Activate WooPay','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14395','34','woopay-beta-merchantrecruitment-short-activate-button-09MAY23','Activate WooPay','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14396','34','woopay-beta-merchantrecruitment-short-activate-learnmore-button2-09MAY23','Learn More','https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-short-activate-learnmore-button2-09MAY23','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14397','35','woopay-beta-merchantrecruitment-short-update-WCPay-09MAY23','Update WooCommerce Payments','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14398','35','woopay-beta-merchantrecruitment-short-update-activate-09MAY23','Activate WooPay','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14399','36','woocommerce-WCSubscriptions-June-2023-updated-needed-Plugin-Settings','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14400','36','woocommerce-WCSubscriptions-June-2023-updated-needed-dismiss','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14401','37','woocommerce-WCReturnsWarranty-June-2023-updated-needed','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14402','37','woocommerce-WCReturnsWarranty-June-2023-updated-needed','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14403','38','woocommerce-WCOPC-June-2023-updated-needed','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14404','38','woocommerce-WCOPC-June-2023-updated-needed','Dismiss','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14405','39','woocommerce-WCGC-July-2023-update-needed','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14406','39','woocommerce-WCGC-July-2023-update-needed','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14407','40','learn-more','Learn more','https://woocommerce.com/document/fedex/?utm_medium=product&utm_source=inbox_note&utm_campaign=learn-more#july-2023-api-outage','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14408','41','plugin-list','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php?plugin_status=all','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14409','41','dismiss','Dismiss','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/admin.php?page=wc-admin','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14410','42','woocommerce-WCStripe-Aug-2023-update-needed','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php?','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14411','42','dismiss','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14412','43','dismiss','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14413','44','dismiss','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14414','45','avalara_q3-2023_noAvaTax','Automate my sales tax','https://woocommerce.com/products/woocommerce-avatax/?utm_source=inbox_note&utm_medium=product&utm_campaign=avalara_q3-2023_noAvaTax','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14415','46','woocommerce-usermeta-Sept2023-productvendors','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/plugins.php','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14416','46','dismiss','Dismiss','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14417','47','woocommerce-STRIPE-Oct-2023-update-needed','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14418','47','dismiss','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14419','48','amazon-mcf-review-button-2023-12-07','Leave a review','https://woocommerce.com/products/woocommerce-amazon-fulfillment/?review&utm_source=inbox_note&utm_medium=product&utm_campaign=amazon-mcf-review-button-2023-12-07','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14420','48','amazon-mcf-support-button-2023-12-07','Request support','https://woocommerce.com/my-account/contact-support/?utm_source=inbox_note&utm_medium=product&utm_campaign=amazon-mcf-support-button-2023-12-07','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14421','49','view_docs','Learn about Deposit schedules','https://woocommerce.com/document/woopayments/deposits/deposit-schedule/?utm_source=inbox_note&utm_medium=product&utm_campaign=view_docs#available-funds','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14422','50','sirt-woo-2024-11-xss-admin','See available updates','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/update-core.php?','unactioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14423','50','sirt-woo-2024-11-xss-admin','Dismiss','#','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14424','51','paypal-braintree-sdk-depreciation-2025-02-20-button','Upgrade now','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/wp-admin/plugins.php','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14425','52','uk-vat-notice-button-2025-04-30','Learn more about this extension','https://wordpress.org/plugins/eu-vat-for-woocommerce/','actioned','',NULL,NULL);
INSERT INTO `wp_wc_admin_note_actions` (`action_id`,`note_id`,`name`,`label`,`query`,`status`,`actioned_text`,`nonce_action`,`nonce_name`) VALUES('14426','54','paypal-braintree-sdk-depreciation-2025-05-30-button','Update now','https://staging-68a5-inditechsites.wpcomstaging.com/wp-admin/wp-admin/plugins.php','unactioned','',NULL,NULL);
-- rewind end page null
